title: Deerfield Math Competition
description: The official website for the annual Deerfield Math Competition
theme: just-the-docs

url: https://deerfieldmc.com

aux_links:
  GitHub: https://github.com/Zo-Bro-23/dmc
  Registration: https://forms.gle/n2kncjX9X1jb3nkaA

aux_links_new_tab: true

nav_external_links:
  - title: Registration
    url: https://forms.gle/n2kncjX9X1jb3nkaA
    opens_in_new_tab: true
  - title: Directions
    url: https://maps.app.goo.gl/5TqAAxtwvBwHmpuz7
    opens_in_new_tab: true

logo: "/assets/logo.png"

gh_edit_link: false

ga_tracking: G-JDCSKYNCE8

search_enabled: true

footer_content: "Copyright Â© 2026 Deerfield Math Competition. All rights reserved."